export default {
  LOAD_CATEGORIES_REQUEST: 'LOAD_CATEGORIES_REQUEST',
  LOAD_CATEGORIES_SUCCESS: 'LOAD_CATEGORIES_SUCCESS',
  LOAD_CATEGORIES_FAILURE: 'LOAD_CATEGORIES_FAILURE',
  LOAD_SUBCATEGORIES_REQUEST: 'LOAD_SUBCATEGORIES_REQUEST',
  LOAD_SUBCATEGORIES_SUCCESS: 'LOAD_SUBCATEGORIES_SUCCESS',
  LOAD_SUBCATEGORIES_FAILURE: 'LOAD_SUBCATEGORIES_FAILURE',
  LOAD_GIFS_REQUEST: 'LOAD_GIFS_REQUEST',
  LOAD_GIFS_SUCCESS: 'LOAD_GIFS_SUCCESS',
  LOAD_GIFS_FAILURE: 'LOAD_GIFS_FAILURE'
}
